config/routes.rb
Rails.application.routes.draw do



  resources :courses do
    resources :posts do
      resources :comments
    end
  end

  resources :app_settings

  devise_for :users, controllers: { registrations: 'user_registrations/registrations'}

  resources :grid_images, only: [:create, :new, :destroy]

  resources :template_ones do
    resources :projects
    resources :grid_image_categories, only: [:create, :new, :destroy]
  end



 
  resources :incoming_contacts

  root to: 'template_ones#show'
  get 'edit_about', to: 'template_ones#edit_about'
  get 'edit_services', to: 'template_ones#edit_services'
  get 'edit_process', to: 'template_ones#edit_process' 
  get 'edit_header', to: 'template_ones#edit_header' 
  get 'edit_contact', to: 'template_ones#edit_contact' 
  get 'edit_action', to: 'template_ones#edit_action' 
  get 'edit_testimonial', to: 'template_ones#edit_testimonial' 
  get 'edit_portfolio_carousel', to: 'template_ones#edit_portfolio_carousel'
  get 'edit_portfolio_carousel_heading', to: 'template_ones#edit_portfolio_carousel_heading'
  get 'edit_portfolio_grid', to: 'template_ones#edit_portfolio_grid'
  get 'edit_footer', to: 'template_ones#edit_footer'
  get 'edit_navigation', to: 'template_ones#edit_navigation'
  get 'edit_newsletter', to: 'template_ones#edit_newsletter'
end 

app/controllers/template_ones_controller.rb
class TemplateOnesController < ApplicationController
  before_action :set_template_one, only: [:show, :edit, :update, :destroy, :edit_about, :edit_services, :edit_process, :edit_header, :edit_contact, :edit_action, :edit_testimonial, :edit_portfolio_carousel, :edit_portfolio_carousel_heading, :edit_portfolio_grid, :edit_footer, :edit_navigation, :edit_newsletter] 
  before_action :authenticate_user!, except: [:show]
  
  before_action :not_admin_user, only: [:edit, :update, :destroy, :index, :edit_about, :edit_services, :edit_process, :edit_header, :edit_contact, :edit_action, :edit_testimonial, :edit_portfolio_carousel, :edit_portfolio_carousel_heading, :edit_portfolio_grid, :edit_footer, :edit_navigation, :edit_newsletter]
  layout 'template_ones' 
  # GET /template_ones
  # GET /template_ones.json
  def index
    flash[:danger] = "Not a valid path." 
    redirect_back(fallback_location: root_path)
    @template_ones = TemplateOne.all
  end

  # GET /template_ones/1
  # GET /template_ones/1.json
  def show
    # if current_user and not current_user.try(:admin?)
    # if current_user && !current_user.try(:admin?)
    #   redirect_to course_posts_path 
    # end
    @projects = Project.all
    @incoming_contact = IncomingContact.new 
    @posts = Post.last(@template_one.testimonial_count).reverse  
    @grid_image_categories = GridImageCategory.all
    @grid_images = GridImage.all
  end

  # GET /template_ones/new
  def new
    @template_one = TemplateOne.new
  end

  # GET /template_ones/1/edit
  def edit
  end

  # POST /template_ones
  # POST /template_ones.json
  def create
    @template_one = TemplateOne.new(template_one_params)

    respond_to do |format|
      if @template_one.save
        format.html { redirect_to @template_one, notice: 'Template one was successfully created.' }
        format.json { render :show, status: :created, location: @template_one }
      else
        format.html { render :new }
        format.json { render json: @template_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /template_ones/1
  # PATCH/PUT /template_ones/1.json
  def update
    respond_to do |format|
      if @template_one.update(template_one_params)
        format.html { redirect_back fallback_location: root_path, notice: 'Template one was successfully updated.' }
        format.json { render :show, status: :ok, location: @template_one }
      else
        flash[:danger] = "There was a problem! " + @template_one.errors.full_messages.to_sentence
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render json: @template_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /template_ones/1
  # DELETE /template_ones/1.json
  def destroy
    @template_one.destroy
    respond_to do |format|
      format.html { redirect_to template_ones_url, notice: 'Template one was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_about
  end

  def edit_services
  end

  def edit_process
  end

  def edit_header
  end

  def edit_contact
    @incoming_contact = IncomingContact.new 
  end

  def edit_action 
  end
 
  def edit_testimonial 
    @posts = Post.last(@template_one.testimonial_count).reverse
  end

  def edit_portfolio_carousel
    @projects = Project.all
  end

  def edit_portfolio_carousel_heading
  end

  def edit_portfolio_grid
    @grid_image_category = GridImageCategory.new
    @grid_image_categories = GridImageCategory.all
    @grid_image = GridImage.new
    @grid_images = GridImage.all
  end

  def edit_footer
  end

  def edit_navigation
  end

  def edit_newsletter
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template_one
      @template_one = TemplateOne.find(1)
    end

    def not_admin_user
      if !current_user.try(:admin?)
        flash[:danger] = "This resource is not available."
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def template_one_params
      params.require(:template_one).permit(
        :about_image_show_default,
        :about_hide, 
        :about_title,
        :about_text,
        :about_text_2,
        :about_image,
        :service_hide,
        :service_icon_1,
        :service_title_1,
        :service_text_1,
        :service_icon_2,
        :service_title_2,
        :service_text_2,
        :service_icon_3,
        :service_title_3,
        :service_text_3,
        :service_icon_4,
        :service_title_4,
        :service_text_4,
        :service_title_5,
        :service_text_5,
        :process_hide, 
        :main_process_title,
        :main_process_title_text,
        :process_icon_1,
        :sub_title_1,
        :process_li_1,
        :process_li_2,
        :process_li_3,
        :process_li_4,
        :process_icon_2,
        :sub_title_2,
        :process_li_5,
        :process_li_6,
        :process_li_7,
        :process_li_8,
        :process_icon_3,
        :sub_title_3,
        :process_li_9,
        :process_li_10,
        :process_li_11,
        :process_li_12,
        :header_hide,
        :header_title, 
        :header_text,
        :header_image,
        :contact_hide,
        :contact_title,
        :contact_text,
        :contact_sender_hide_name,  
        :contact_sender_name,
        :contact_sender_hide_email,
        :contact_sender_email,
        :contact_sender_hide_phone,
        :contact_sender_phone,
        :contact_sender_hide_message,
        :contact_sender_message,
        
        :email_address_1, 
        :email_address_2, 
        :email_address_3, 
        :header_svg,
        :header_use_default_svg,
        :header_use_default_image,

        :action_hide,
        :action_text_1,
        :action_text_2,
        :action_text_3,
        :action_text_4,
        :action_text_5,
        :action_text_6,   
        :action_text_7,
        :action_button_text,
        :action_use_default_image,
        :action_image, 
        :testimonial_hide,
        :testimonial_count,
        :portfolio_carousel_hide,
        :portfolio_header_hide,
        :portfolio_header_title,
        :portfolio_header_text,
        :portfolio_grid_hide,
        :portfolio_grid_title,
        :portfolio_grid_text,
        :footer_hide,
        :footer_hide_telephone,
        :footer_icon_telephone,
        :footer_telephone_title,
        :footer_telephone_number,
        :footer_hide_address,
        :footer_icon_address,
        :footer_address_title,
        :footer_address_street,
        :footer_address_city,
        :footer_address_state,
        :footer_address_postal_code,
        :footer_hide_email,
        :footer_icon_email,
        :footer_email_title,
        :footer_email_address,
        :footer_hide_social_1, 
        :footer_social_icon_1,
        :footer_social_url_1,
        :footer_hide_social_2,
        :footer_social_icon_2,
        :footer_social_url_2,
        :footer_hide_social_3,
        :footer_social_icon_3,
        :footer_social_url_3,
        :footer_hide_social_4,
        :footer_social_icon_4,
        :footer_social_url_4,
        :footer_hide_social_5,
        :footer_social_icon_5,
        :footer_social_url_5,
        :footer_hide_social_6,
        :footer_social_icon_6,
        :footer_social_url_6,
        :footer_use_default_image,
        :footer_image,
        :navigation_hide,
        :navigation_title,
        :newsletter_hide,
        :newsletter_title

        )
    end
end

app/helpers/template_ones_helper.rb
module TemplateOnesHelper
end

app/views/template_ones/_form.html.erb
<%= simple_form_for(@template_one) do |f| %>


  <div class="form-inputs">

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/template_ones/edit.html.erb
<h1>Editing Template One</h1>

<%= render 'form', template_one: @template_one %>

<%= link_to 'Show', @template_one %> |
<%= link_to 'Back', template_ones_path %>

app/views/template_ones/edit_about.html.erb
<%= render 'template_ones/edit_partials/about' %> 
<div class='container'>
  <%= bootstrap_flash %>  
  <br>
  <%= link_to "Home", root_path, class: "btn btn-outline-info btn-sm" %>
  <br><br>
  <%= simple_form_for(@template_one) do |f| %>
  <div class="form-inputs">
    <%= f.input :about_hide, label: "Hide this module on main page?" %> 
    <%= f.input :about_title %>
    <%= f.input :about_text %> 
    <%= f.input :about_text_2 %> 
    <%= f.input :about_image_show_default, label: "Show default images?" %>
    <label>Add custom image (600 X 400)</label>
    <%= f.input :about_image, as: :file, label: false %> 
  </div>
  <div class='container'>
    <label>Image Preview</label><br>
    <%= image_tag @template_one.about_image_url(:small) if @template_one.about_image.present? %> 
  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit, data: {disable_with: 'One moment please...'} %> 
    | <%= link_to "Home", root_path, class: "btn btn-default" %> 
  </div>
  <% end %>
</div>

app/views/template_ones/edit_footer.html.erb
<%= render 'template_ones/edit_partials/footer' %> 
<div class='container'>
  <%= bootstrap_flash %>  
<br>
  <%= link_to "Home", root_path, class: "btn btn-outline-info btn-sm" %>
<br><br>
  <%= simple_form_for(@template_one) do |f| %>
  <%= f.input :footer_hide, label: "Hide this module on main page?" %>

  <div class="row">
    <div class="col-sm-4">
      <h5>Telephone</h5>
      <%= f.input :footer_hide_telephone, label: "Hide Telephone info?" %>
      <span id='hide_telephone_input'>
        <label>Telephone Icon</label>
        <i id='footer_icon_telephone_input' class="fa fa-<%= @template_one.footer_icon_telephone %> fa-fw fa-2x"></i>
        <%= f.input :footer_icon_telephone, collection: TemplateOne::FA_ICONS, include_blank: false, label: false %>
        <%= f.input :footer_telephone_title %>
        <%= f.input :footer_telephone_number %>
        <h6>Background Image</h6>
        <%= f.input :footer_use_default_image, label: "Use the footer default image?" %>
        <h6>Add a Custom Image(1500 X 798)</h6>
        <%= f.input :footer_image %>
      </span>
    </div>
    <div class="col-sm-4">
      <h5>Address</h5>
      <%= f.input :footer_hide_address, label: "Hide Address info?" %>
      <span id='hide_address_input'>
      <label>Address Icon</label>
      <i id='footer_icon_address_input' class="fa fa-<%= @template_one.footer_icon_address %> fa-fw fa-2x"></i>
      <%= f.input :footer_icon_address, collection: TemplateOne::FA_ICONS, include_blank: false, label: false %>
      <%= f.input :footer_address_title %>
      <%= f.input :footer_address_street %>
      <%= f.input :footer_address_city %>
      <%= f.input :footer_address_state %>
      <%= f.input :footer_address_postal_code %>
      </span>
    </div>
    <div class="col-sm-4">
      <h5>Email</h5>
      <%= f.input :footer_hide_email, label: "Hide Email info?" %>
      <span id='hide_email_input'>
      <label>Email Icon</label>
      <i id='footer_icon_email_input' class="fa fa-<%= @template_one.footer_icon_email %> fa-fw fa-2x"></i>
      <%= f.input :footer_icon_email, collection: TemplateOne::FA_ICONS, include_blank: false, label: false %>
      <%= f.input :footer_email_title %>
      <%= f.input :footer_email_address %>
      </span>
    </div>
  </div>
  <br>
  <hr>
  <div class="row">
    <div class="col-sm-4">
      <h5>Socal Link 1</h5>
      <%= f.input :footer_hide_social_1, label: "Hide this from the view?" %> 
      <span id='hide_social_1_input'>
      <label>Social Link 1 Icon</label>
      <i id='footer_social_icon_1_input' class="fa fa-<%= @template_one.footer_social_icon_1 %> fa-fw fa-2x"></i>
      <%= f.input :footer_social_icon_1, collection: TemplateOne::FA_BRAND_ICONS, include_blank: false, label: false %>
      <%= f.input :footer_social_url_1, label: "Set link: 'example.com'" %>
      </span>
    </div>
    <div class="col-sm-4">
      <h5>Socal Link 2</h5>
      <%= f.input :footer_hide_social_2, label: "Hide this from the view?" %>
      <span id='hide_social_2_input'>
      <label>Social Link 2 Icon</label>
      <i id='footer_social_icon_2_input' class="fa fa-<%= @template_one.footer_social_icon_2 %> fa-fw fa-2x"></i>
      <%= f.input :footer_social_icon_2, collection: TemplateOne::FA_BRAND_ICONS, include_blank: false, label: false %>
      <%= f.input :footer_social_url_2, label: "Set link: 'example.com'" %>
      </span>
    </div>
    <div class="col-sm-4">
      <h5>Socal Link 3</h5>
      <%= f.input :footer_hide_social_3, label: "Hide this from the view?" %>
      <span id='hide_social_3_input'>
      <label>Social Link 3 Icon</label>
      <i id='footer_social_icon_3_input' class="fa fa-<%= @template_one.footer_social_icon_3 %> fa-fw fa-2x"></i>
      <%= f.input :footer_social_icon_3, collection: TemplateOne::FA_BRAND_ICONS, include_blank: false, label: false %>
      <%= f.input :footer_social_url_3, label: "Set link: 'example.com'" %>
      </span>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-sm-4">
      <h5>Socal Link 4</h5>
      <%= f.input :footer_hide_social_4, label: "Hide this from the view?" %>
      <span id='hide_social_4_input'>
      <label>Social Link 4 Icon</label>
      <i id='footer_social_icon_4_input' class="fa fa-<%= @template_one.footer_social_icon_4 %> fa-fw fa-2x"></i>
      <%= f.input :footer_social_icon_4, collection: TemplateOne::FA_BRAND_ICONS, include_blank: false, label: false %>
      <%= f.input :footer_social_url_4, label: "Set link: 'example.com'" %>
      </span>
    </div>
    <div class="col-sm-4">
      <h5>Socal Link 5</h5>
      <%= f.input :footer_hide_social_5, label: "Hide this from the view?" %>
      <span id='hide_social_5_input'>
      <label>Social Link 5 Icon</label>
      <i id='footer_social_icon_5_input' class="fa fa-<%= @template_one.footer_social_icon_5 %> fa-fw fa-2x"></i>
      <%= f.input :footer_social_icon_5, collection: TemplateOne::FA_BRAND_ICONS, include_blank: false, label: false  %>
      <%= f.input :footer_social_url_5, label: "Set link: 'example.com'" %>
      </span>
    </div>
    <div class="col-sm-4">
      <h5>Socal Link 6</h5>
      <%= f.input :footer_hide_social_6, label: "Hide this from the view?" %>
      <span id='hide_social_6_input'>
      <label>Social Link 6 Icon</label>
      <i id='footer_social_icon_6_input' class="fa fa-<%= @template_one.footer_social_icon_6 %> fa-fw fa-2x"></i>
      <%= f.input :footer_social_icon_6, collection: TemplateOne::FA_BRAND_ICONS, include_blank: false, label: false  %>
      <%= f.input :footer_social_url_6, label: "Set link: 'example.com'" %> 
      </span>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit, data: {disable_with: 'One moment please...'} %> 
    | <%= link_to "Home", root_path, class: "btn btn-default" %> 
  </div>
  <% end %>
</div>
<hr>

app/views/template_ones/edit_header.html.erb
<%= render 'template_ones/edit_partials/header' %> 
<div class='container'>
  <%= bootstrap_flash %>  
  <br>
  <%= link_to "Home", root_path, class: "btn btn-outline-info btn-sm" %>
  <br><br>
  <%= simple_form_for(@template_one) do |f| %>
  <div class="form-inputs">
    <%= f.input :header_title%>
    <%= f.input :header_text %>
    <%= f.input :header_use_default_image, label: 'Use Template Default Image?' %>
    <label>Upload Custom Image</label>
    <%= f.input :header_image, as: :file, label: false %>  
    <%= f.input :header_use_default_svg, label: 'Use Template SVG Image?' %>
    <label>Upload Custom SVG</label>
    <%= f.input :header_svg, as: :file, label: false %>  
  </div>
  <div class="form-actions">
    <%= f.button :submit, data: {disable_with: 'Updating Header...'} %> 
    | <%= link_to "Home", root_path, class: "btn btn-default" %> 
  </div>
  <% end %>
</div>
<br><br><br><br><br>

app/views/template_ones/edit_newsletter.html.erb
<%= render 'template_ones/edit_partials/newsletter' %> 
<div class='container'>
  <%= bootstrap_flash %>  
  <br>
  <%= link_to "Home", root_path, class: "btn btn-outline-info btn-sm" %>
  <br><br>
  <%= simple_form_for(@template_one) do |f| %>
  <div class="form-inputs">
    <%= f.input :newsletter_hide, label: "Hide this module on main page?" %> 
    <%= f.input :newsletter_title %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, data: {disable_with: 'Updating Newsletter'} %> 
    | <%= link_to "Home", root_path, class: "btn btn-default" %> 
  </div>
  <% end %>
</div>

app/views/template_ones/edit_portfolio_carousel.html.erb
<%= render 'template_ones/edit_partials/portfolio_carousel' %> 
<%= render 'template_ones/edit_partials/portfolio_modal_1' %>
<%= render 'template_ones/edit_partials/portfolio_modal_2' %>
<%= render 'template_ones/edit_partials/portfolio_modal_3' %>
<%= render 'template_ones/edit_partials/portfolio_modal_4' %>
<%= render 'template_ones/partials/static_assets/static_assets' %>
<div class='container'>
  <%= bootstrap_flash %> 
  <br>
  <%= link_to "Home", root_path, class: "btn btn-outline-info btn-sm" %>
  <br><br>
  <%= simple_form_for(@template_one) do |f| %>
  <div class="form-inputs">
    <%= f.input :portfolio_carousel_hide, label: "Hide this module on main page?" %> 
  </div>
  <div class="form-actions">
    <%= f.button :submit, data: {disable_with: 'One moment please...'} %> 
    | <%= link_to "Home", root_path, class: "btn btn-default" %> 
  </div>
  <% end %>
</div>
<br>
<%= link_to "Add Project", new_template_one_project_path(@template_one), class: 'btn btn-success' %>
<br><br><br><br><br><br><br><br>

app/views/template_ones/edit_portfolio_carousel_heading.html.erb
<%= render 'template_ones/edit_partials/portfolio_carousel_heading' %> 
<div class='container'>
  <%= bootstrap_flash %>  
  <br>
  <%= link_to "Home", root_path, class: "btn btn-outline-info btn-sm" %>
  <br><br>
  <%= simple_form_for(@template_one) do |f| %>
  <%= f.input :portfolio_header_hide, label: "Hide this module on main page?" %>  
  <div class="form-inputs col-sm-8 mx-auto">
    <%= f.input :portfolio_header_title %>
    <%= f.input :portfolio_header_text %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, data: {disable_with: 'One moment please...'} %> 
    | <%= link_to "Home", root_path, class: "btn btn-default" %> 
  </div>
  <% end %>
</div>
<br><br><br><br>

app/views/template_ones/edit_process.html.erb
<%= render 'template_ones/edit_partials/process' %> 
<div class='container'>
  <%= bootstrap_flash %>  
  <br>
  <%= link_to "Home", root_path, class: "btn btn-outline-info btn-sm" %>
  <br><br>
  <%= simple_form_for(@template_one) do |f| %>
  <div class="form-inputs">
    <%= f.input :process_hide, label: "Hide this module on main page?" %> 
    <div class="row">
      <div class="col-sm-3">
        <h5>Title & Text</h5>
        <%= f.input :main_process_title, label: 'Main Title' %>
        <%= f.input :main_process_title_text, label: 'Main Title Text' %>
      </div>
      <div class="col-sm-3">
        <h5>Icon & Text 1</h5>
        <label>Icon 1</label>
        <i id='process_icon_1_input' class="fa fa-<%= @template_one.process_icon_1 %> fa-fw fa-2x"></i>
        <%= f.input :process_icon_1, collection: TemplateOne::FA_ICONS, include_blank: false, label: false %>
        <%= f.input :sub_title_1, label: 'Icon Text' %>
      </div>
      <div class="col-sm-3">
        <h5>Icon & Text 2</h5>
        <label>Icon 2</label>
        <i id='process_icon_2_input' class="fa fa-<%= @template_one.process_icon_2 %> fa-fw fa-2x"></i>
        <%= f.input :process_icon_2, collection: TemplateOne::FA_ICONS, include_blank: false, label: false %>
        <%= f.input :sub_title_2, label: 'Icon Text' %>
      </div>
      <div class="col-sm-3">
        <h5>Icon & Text 3</h5>
        <label>Icon 3</label>
        <i id='process_icon_3_input' class="fa fa-<%= @template_one.process_icon_3 %> fa-fw fa-2x"></i>
        <%= f.input :process_icon_3, collection: TemplateOne::FA_ICONS, include_blank: false, label: false %>
        <%= f.input :sub_title_3, label: 'Icon Text' %>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-sm-4">
        <h5>List Items Icon 1</h5>
        <%= f.input :process_li_1, label: 'List Item 1' %>
        <%= f.input :process_li_2, label: 'List Item 2' %>
        <%= f.input :process_li_3, label: 'List Item 3' %>
        <%= f.input :process_li_4, label: 'List Item 4' %>
      </div>
      <div class="col-sm-4">
        <h5>List Items Icon 2</h5>
        <%= f.input :process_li_5, label: 'List Item 1' %>
        <%= f.input :process_li_6, label: 'List Item 2' %>
        <%= f.input :process_li_7, label: 'List Item 3' %>
        <%= f.input :process_li_8, label: 'List Item 4' %>
      </div>
      <div class="col-sm-4">
        <h5>List Items Icon 3</h5>
        <%= f.input :process_li_9, label: 'List Item 1' %>
        <%= f.input :process_li_10, label: 'List Item 2' %>
        <%= f.input :process_li_11, label: 'List Item 3' %>
        <%= f.input :process_li_12, label: 'List Item 4' %>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit, data: {disable_with: 'One moment please...'} %> 
    | <%= link_to "Home", root_path, class: "btn btn-default" %> 
  </div>
  <% end %>
</div>
<br><br><br><br>

app/views/template_ones/edit_service.html.erb
<%= render 'template_ones/edit_partials/service' %> 


<div class='container'> 
<%= bootstrap_flash %>  
<%= simple_form_for(@template_one) do |f| %>


  <div class="form-inputs">
    <%= f.input :service_hide, label: "Hide this module on main page?" %> 
    <%= f.input :service_icon_1 %>
    <%= f.input :service_title_1 %>
    <%= f.input :service_text_1 %>
    <%= f.input :service_icon_2 %>
    <%= f.input :service_title_2 %>
    <%= f.input :service_text_2 %>
    <%= f.input :service_icon_3 %>
    <%= f.input :service_title_3 %>
    <%= f.input :service_text_3 %>
    <%= f.input :service_icon_4 %>
    <%= f.input :service_title_4 %>
    <%= f.input :service_text_4 %>
    <%= f.input :service_icon_5 %>
    <%= f.input :service_title_5 %>
    <%= f.input :service_text_5 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, data: {disable_with: 'One moment please...'} %> 
     | <%= link_to "Home", root_path, class: "btn btn-default" %> 
  </div>
<% end %>
</div>

app/views/template_ones/edit_services.html.erb
<%= render 'template_ones/edit_partials/services' %> 
<div class='container'>
  <%= bootstrap_flash %>  
  <br>
  <%= link_to "Home", root_path, class: "btn btn-outline-info btn-sm" %>
  <br><br>
  <%= simple_form_for(@template_one) do |f| %>
  <div class="form-inputs">
    <div class="col-sm-6 mx-auto">
      <h3>Title</h3>
      <%= f.input :service_hide, label: "Hide this module on main page?" %> 
      <%= f.input :service_title_1 %>
      <%= f.input :service_text_1 %>
    </div>
    <br>
    <hr>
    <div class="row">
      <div class="col-sm-3">
        <h3>Title</h3>
        <label>Icon 1 </label>
        <i id='service_icon_1_input' class="fa fa-<%= @template_one.service_icon_1 %> fa-2x"></i>
        <%= f.input :service_icon_1, collection: TemplateOne::FA_ICONS, include_blank: false, label: false %>
        <%= f.input :service_title_2 %>
        <%= f.input :service_text_2 %>
      </div>
      <div class="col-sm-3">
        <h3>Title</h3>
        <label>Icon 2 </label>
        <i id='service_icon_2_input' class="fa fa-<%= @template_one.service_icon_2 %> fa-2x"></i>
        <%= f.input :service_icon_2, collection: TemplateOne::FA_ICONS, include_blank: false, label: false %>  
        <%= f.input :service_title_3 %>
        <%= f.input :service_text_3 %>
      </div>
      <div class="col-sm-3">
        <h3>Title</h3>
        <label>Icon 3 </label>
        <i id='service_icon_3_input' class="fa fa-<%= @template_one.service_icon_3 %> fa-2x"></i>
        <%= f.input :service_icon_3, collection: TemplateOne::FA_ICONS, include_blank: false, label: false %>
        <%= f.input :service_title_4 %>
        <%= f.input :service_text_4 %>
      </div>
      <div class="col-sm-3">
        <h3>Title</h3>
        <label>Icon 4 </label>
        <i id='service_icon_4_input' class="fa fa-<%= @template_one.service_icon_4 %> fa-2x"></i>
        <%= f.input :service_icon_4, collection: TemplateOne::FA_ICONS, include_blank: false, label: false %>
        <%= f.input :service_title_5 %>
        <%= f.input :service_text_5 %>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit, data: {disable_with: 'One moment please...'} %> 
    | <%= link_to "Home", root_path, class: "btn btn-default" %> 
  </div>
  <% end %>
</div>
<br><br><br><br> 

app/views/template_ones/new.html.erb
<h1>New Template One</h1>

<%= render 'form', template_one: @template_one %>

<%= link_to 'Back', template_ones_path %>